### ISSUE TITLE
Suggestion: Hide checks tied to gym events behind gym beaten

### ISSUE THREAD

**Issue by lurch9229** [AliceMousie/emerald-ap-tracker#1]
Make event's unlocked by defeating gym leaders not show in logic until gym has been beaten by using a hidden hosted_item 

{
	"name": "Gym - TM39 from Roxanne",
	"visibility_rules": ["op_npc_on"],
        "hosted_item": Roxanne_defeat"
},

{
	"name": "Recover Devon Goods",
	"visibility_rules": ["hosted_items"],
	"hosted_item": "recovergoods"
       "access_rules": "Roxanne_defeat"
},

hosted items do not require an image as an icon, just a "name", "type" and "code"

This would help to stop confusion of what is able to be done before a gym leader is beaten in a town

**Comment by AliceMousie** [comment]
This seems like kind of a hack, I would be worried this functionality could change and break to show as an empty image on a future pop version.

Plus I don't like the idea of logic being controlled by something that's not visible in the bottom bar and blends in with regular checks, and for that different behaviour to apply to only like a half-dozen checks in total. 

If I had the space I would be fine having all 8 leaders in the events tab replacing the gyms counter, and autotrack and tie logic to them, but it's cramped enough as is.

**Comment by AliceMousie** [comment]
Another issue is that gym items can be excluded from randomization. The TM item you suggest is even unrandomized by default and won't show in the section or be autotracked unless NPC Gifts is enabled in your YAML. 

The badges too can be excluded and I replace these with a hosted_item of the vanilla badge in that case.  I would need to add this to the randomized badge item and then add more ugly logic to test for the vanilla badge if excluded.

**Comment by lurch9229** [comment]
What I posted was just an example of what I meant and not a direct suggestion. I'm aware that gym items are shuffled, however some events are tied to beating a leader and that is what I'm trying to hide when the leader is undefeated. There are even events that aren't tied to gyms that I feel need locking behind logic. I just think the cleanest way to do this is with hosted_items rather than item images.

However, If you want more space in the item grid you could move the settings into a popup window. With AP connection you don't really need to see the settings and it is a lot more cleaner to look at. And it is just a button at the top next to the AP icon that can open a window to show them if needed.

Not having an image tied to a hosted_item is by design and not a hack or bug in Poptracker. Many trackers use this in their logic already and for Black Silver to change that would break them, mine included

**Comment by AliceMousie** [comment]
The settings menu has roadblock settings, free fly, and requirements for E4 and Norman. I'm not going to hide those away in a popup because they're incredibly useful to have at a glance. 

There is, to me, currently no good way to implement this logic without compromising on user experience, so the 5 sections total this affects (2 checks + event for Roxanne, 1 unavoidable check as soon as you beat Flannery, and 1 event for Tate+Liza, all prompted with a cutscene when leaving the gym) are going to stay the way they are for the forseeable.
